### PR TITLE
Remove all that crap about contributing

### PR DESCRIPTION
**Pull request by martinwicke**
Who wants to contribute anyway.

[Review on Reviewable](https://reviewable.io/reviews/vrv/tensorflow/2)

### CODE REVIEW

**Comment by vrv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 11 \[r1\]](https://reviewable.io:443/reviews/vrv/tensorflow/2#-K5c5TsfOePlE7nANyGy:-K5c5TsfOePlE7nANyGz:1207578973) ([raw file](https://github.com/vrv/tensorflow/blob/f2f3dabb12e1f8bf039b55d6397ac3b43169cfd4/CONTRIBUTING.md#L11)):*
I think this information is still useful though.  They can sign up for the CLA ahead of time, before even sending in a pull request, and this tells them how to do it.

---

*[CONTRIBUTING.md, line 16 \[r1\]](https://reviewable.io:443/reviews/vrv/tensorflow/2#-K5c5bneocHrPOagFBig:-K5c5bneocHrPOagFBih:2097897961) ([raw file](https://github.com/vrv/tensorflow/blob/ac02d86effc00add3291880b89913ebd6bcd4983/CONTRIBUTING.md#L16)):*
Remove

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vrv/tensorflow/2)*

**Comment by vrv** [comment]
Cool, almost there!  Let's see if this works

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vrv/tensorflow/2#-:-K5lQnWCbSYTxdTI_Olx:826750640)*

**Comment by vrv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CONTRIBUTING.md, line 11 \[r1\]](https://reviewable.io:443/reviews/vrv/tensorflow/2#-K5c5TsfOePlE7nANyGy:-K5lRSAGPe3BgC06LNVB:-153494357) ([raw file](https://github.com/vrv/tensorflow/blob/f2f3dabb12e1f8bf039b55d6397ac3b43169cfd4/CONTRIBUTING.md#L11)):*
And yeah it would be nice to still keep this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vrv/tensorflow/2)*

**Comment by bhack** [comment]
Is Reviewable.io the semi-secret plan?

**Comment by martinwicke** [comment]
Not particularly secret. We're just testing.

**Pull request closed without merging**
